FROM ubuntu:14.04
# this is an LTS release of Ubuntu
MAINTAINER Ovidiu-Florin Bogdan "ovidiu.bogdan@movidius.com"
RUN apt-get update
RUN apt-get dist-upgrade -yy
RUN apt-get install -yy build-essential
